[connections.receipt_db]
url = "sqlite:///data/receiptmanager.db"

[database]
db_name = "data/receiptmanager.db"

[security]
salt = "6xZ"

[fernet]
fernet_key="Pc87_FaT23u-EyECfvMQyWqaHmrBzVfzU3GZRuIn_ec="